apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sealed-secrets

labels:
  - pairs:
      app.kubernetes.io/name: sealed-secrets
      app.kubernetes.io/component: sealed-secrets-controller
      app.kubernetes.io/part-of: infrastructure
      app.kubernetes.io/managed-by: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/bitnami-labs/sealed-secrets/v0.37.0/helm/sealed-secrets/crds/bitnami.com_sealedsecrets.yaml

helmCharts:
  - name: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
    version: 2.18.6
    namespace: sealed-secrets
    valuesFile: values.yaml

# Enable Stakater Reloader for automatic reloads on ConfigMap/Secret changes
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /metadata/annotations/reloader.stakater.com~1auto
        value: "true"