createController: true # Set to false if controller is already deployed i.e. bootstrapped

fullnameOverride: sealed-secrets

existingSecret: sealed-secrets-key
# Disable key generation since we're providing our own
key:
  generate: false

serviceAccount:
  create: true
  name: sealed-secrets-sa

rbac:
  create: true

# Optionally, if you want to customize other settings:
controller:
  affinity: {}
  tolerations: []
  nodeSelector: {}
