---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-password
  namespace: external-dns
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgA52bEj/RzF+LWgonLUnNMTaiQsZ7ZrSZHOW5gB/chiU/3VHvMzlxJP1QH7z92BLsqMfi14hD6rd67MkhCsIPvQ3Sxdx5WefNNWhzfw5EcYEVqcHj6wedkK60uEoO2JkPVBsjNdZiyyPDKT/no3pjpmFqlgaPQ0Ly1Gu0Am0klLYdOYQ5YmiGJy7mTvEgobmaxegyDzWrKTaIHenAz4TCGNazcljrBhZmIzBEAKoVZpQNMmgoXQ9y8dp3hWkMRENBrC/DW7fFrlDkGw0Z+A/Ywt9UhSog+/x57zcLlGN7nNazJS1D+3+edRlEduc4Z1q89yRUbLGKrLF6E5cN8LDJsiXxN/We05UYoeLfz+6vt50mHYgP3udsciOlRYQdE8TeoeowmFylskfvm51DQxa1Jz/jYAJlv3wVV39KjgzIHVpbEHjPDpEX7OT4Hr8ajra9ebaz3CjbdXrT0/jJEc/CVBhucrlgNbKf67kFk7S7R/Et4PbBt7T+do9/Yr93tkj9T2Xk/5zIHq2PacSGlrIIilhGUbz9AdER3hd5PGziJ8Acv8ShOElVFJ80/Pvphr0RJGOoWjsEiCkv9Eg0RcZORWvcFZW8fNeXL7SqNt13SXkEBmv1/V2YjsLauXul6MahmeChRzSUmxHfJ5yRBr1NnjBB2Tk3hyAGZLWDDqLQauv9ILLhse06oubDYHMWw9h8irfE9lujb9tw==
  template:
    metadata:
      name: pihole-password
      namespace: external-dns
