---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-acme-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAt5KXwdzdVrKCMGF8bxrV5esAbuF/u061nU09AAXnH0Lmk125v2q5KH6g+UNNIGOmGW9aojocarzfWnSJecLG0z2AU92AduU3iftESS2f4oIOUEDx0PhsJXATp+IZxpGpOgDM4lyV6MIW1V8pwV5Ls5K9suwtRoDYjbD8rwRxAzNQLOPBFxaseuM3WKlt4hu+N0E+6QNY+67nLcIOprqqe90Mcbuao/t7XhBUdxjNf3crBt9++F3Pp3VNGRTUNFDuaLrIzPT5WnXXL6vFBLYEmmjzo6uUehww3JVRTeRJvv+c27zLjWJNu+unV9K3bP4dUkjg+7XatBEL2VlxpJmcNz076+Oy/ZcGsNoyVIrC2IIglp+VQch+pVLTYrsoCw1Y2feq8mBEvhSjyCjoDt1kFU/VXKt3vqo2gHrMBQ4tECp0g1MimzQPmkWOMyo10lwLxIKOXG4/zR22ANw7oAVtLdq9KQHhKjr987pSD+B4dsRVSlYopoxoQqpShVa27j5Q6fjGyk7eiUFIFEYhTxLKfAKjX69LI1OpAhKs6pyjLidgVuE6s3hTLM4BsnzTEZ01f5374ytXS14gJGR/Fps4BkWkK8HNA0cVQU0AQ91bUWlo85tld+I8u7TtGNQmsYU1FNUiklmM3FKyjhgeC3VJsQBv/dLEzF6qDhbGQQ0Isi/tHk2evwzy/ltZXmlN8dx5sh45HbrM8eD5gVijhY3f6CK/5x1gMuyjBhgrCrxtonUUBOTr3MLSwiRwEDlVR0y8/AiBC9Q==
  template:
    metadata:
      name: cloudflare-acme-api-token
      namespace: cert-manager
