---


- name: Set project fact
  ansible.builtin.set_fact:
    cilium_project:
      release:
        cli:
          file: '{{ cilium_vars.release.cli.version }}/{{ cilium_vars.release.cli.file }}'
          url: "{{
            '/'.join(['https://github.com',
              cilium_vars.release.cli.repository.org,
              cilium_vars.release.cli.repository.name, 'releases', 'download'])
            }}"
        gateway_api:
          file: '{{ cilium_vars.release.gateway_api.version }}/{{ cilium_vars.release.gateway_api.file }}'
          url: "{{
            '/'.join(['https://github.com',
              cilium_vars.release.gateway_api.repository.org,
              cilium_vars.release.gateway_api.repository.name, 'releases', 'download'])
            }}"
  run_once: true

- name: Set resources fact
  ansible.builtin.set_fact:
    cilium_resources:
      release:
        - file: '{{ cilium_vars.release.cli.file }}'
          url: '{{ cilium_project.release.cli.url }}/{{ cilium_project.release.cli.file }}'
  run_once: true