---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-redis
  namespace: argocd
spec:
  encryptedData:
    auth: AgBJmHb3yikekGzZJeIfuoTFJwExByByMwr0DhBDfE4c6izOGXntjrN9Aw6X8YcQkYb/H4s/6N5oGn0R3E5GCWwEM+NEDU3IPuw/9tQrwuT67maFHR76VX61oGEj7DUsUjPsZngVPS9lwChJIRBt27PwqOh9q/2mTBqnPoPutcd8vvvEtH0PJEWWBySE/LUcoK6n13BiuePk2R0xXOFst3ZO28USl6dH07xz+C+YoSR38xEQ7h1FB2HebFQFnNqDAXEoa9OkpaVVz8UIXkr6p3HxyJB66MvMcg7v98gWA1k1wWiOObso6pJ66sqIj+ygUs15Hm1ec+H2QlnC3j19FfM717YUPWVw/YdjYsc/MX2t2LuVkaxaCyDMKhHmRbwNeTQFX319HRkg8rb8CJevDIt1mN3Ba0r55P3uKi22NWNhZe6uIKgBQPdPMOuBQ7rybVgqbkTwCJOzhOWoMyygX7sJFWTYhCHqSN08gWhBQt+/VrJufnCYHkLuAWqTkW3gn1bVqM/nFUHLOqanIJuErYmiCcOhT7wcDSHQvRz35paWbXX2ZCI87yvJFgbvx1G+RPszxuu7+cXtzyA0Lw6RxTpaCPsQTmKdxKm0EMmCTsIpoY5hw9ARLRPTBoAZgWkqPTEOdYC7vbfteJPbcsBb9cSDdqV4UacWMZL0AiUI6Jq2h4+07H7JA5banONDSHsRPnVyBVt9mLTklaoTdn9Up8rDUFTe
  template:
    metadata:
      name: argocd-redis
      namespace: argocd
