---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-redis
  namespace: argocd
spec:
  encryptedData:
    auth: AgBmBO1ntyPuTviiMn25rNEJMjniGD8bz18jqMY0q34aMNEKEazJ2jEEUXmresAaiGOhxFI+UGUfBio+FBfyrcV6KV17CUFAcork/99Tf58HmIG75RYUhlILO88NWDe0bQDjGU4CgTPiNMIavPtFv5YZKL3FZML3caBpJ7EwmXeVQJtZteoa5Umsjnyxn/YmKMPTazSSu7nPdr8/qYBpoAM9JnxtrrgoKCJe0Q4sFjWchvmdTkaiMI4GE4dvUurBLsVKIsLbFbzhS5fUPZj4/Dzo6qJWdCdD0IeO19HHFVqe0q7sXXJ4Fmp3K5FMzPV7Dor3IN2V9N01nXCVvCvr1ZTdzUakDBwWMYQq45BcjEQgNg8qGszRwavtEbjSUctqQvkPFps2rYVwDvmSX5XRyGbRyY3EQJhnvyFTXCqXwiJ+fJwJNQmwkVek/IoGB845Qh5wAW3GGT4veCgDgWKd+uAbtXTQRiqxWt7865csoSaE2NfKjopceC2NCzmeYgFPqy8yZrMjAXMJvhBRxHl2RYYSad2ahZIhhvUeHSoSBfSQip6wt7wAlIMVsXj6n4mZXE6vE+b55/2eOTUBJMq0sUcYh6zsW4bBGrLKJ7VNTKrjr4BssHhGy5CND8Jk3zbcbB2RU9Z0wCoPimWjJjnl58oOlg2M3uM6wJmqzLaLwjRLasvT01RY36yAB2QwsHiM4DD/USIbPmVzcfPClvLo5O4aLHyL
  template:
    metadata:
      name: argocd-redis
      namespace: argocd
