---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-credentials
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgBTxuXlNwmQAzHT7T5UC2YQVW1VqaWVWtA3l6FFr0gv5D1vblG00iaedo2c/ayaQA5w3EZOuqPjIgrVFg85xMvkBFx5eVpf4CmlPufoIlqofxVLaaRnU8doYAw/vnM1b1fqil235adlE0tc0itCiMOLw8npMhCh0lKHHQa4JPYcvweM/Hocp2q1DGsV+1Re40JOkP9vIwVcOX3PgJjL935EwO9f+3E0xlSY0Kn808mlJzS9CFRiQKx/YtC20Uv/PVRFCmA02r6qfUB+6S246QCtSAo20igclrpXHdbapmrE3OoX2PhP9pkzMCEGh4sVuCEHgZ2chmwJKZcuP+BKB2voHNP/+2W4LK/Ercg9wnOQoYBWMcxOb+1ITGzbXDbSNPnyrvcTRD0ATzIiF975KFEE1QQv7HVZ1jIl+qoO7yiqXqTbWDechtf5MsQEQ/ql9mdS3EJzybdPnWtpwtzG4dEjKcJEoq81u7KfRoxYY6bw6IDFzqpmWBsBcWe5Mhu2ZTEfMm/x9C21hdwbI7/Qbt0s7Vh/eNy6S8N0BX0BYMJ9sMdvGGBXD7V2WpBP6CulbLrK12M5Ajc+82kEHA5nC/yobeUZV1KPifi9fkd5rfjBdaWE58N43fxaGFYboAg/DfpauzFF6tDtki/ge2zwl7Nwipnv+FJOEG0IFn0YZ9ocNxkecDfyczHv5R6aM9rs4s3K8/zr+TC7yE2eys5hYKlw
    admin-user: AgCW+POAo4OPFoQIyEfAHL87HNasA9pfsviqmbAx51dDGAMnSTOFHd3L/JUXKV3o2dbj4XMJOBupLPw3eg/Vn1+qxOTyTC98ZFmjfdpIG75C/Me65eOEu0w7kOcbgCyxcWkklQeq/a/pkL9dBK0EBZWfUtFamfJ8oxxcXwWJSniXrzNaStxTxcBaNaXT4rWnu4ZFTzTQIwWN7Cl4rsIln1ilBn+a2veaYoEg/mEsYtfDJSBMNY3AvGLpOcvktBKSP5xW0HGqJL4BaP0eEhTfSUo16kveMFduIkYEz758srEKcNbVQzPlaWCMdbKEQ8mi6fK8g/XoPCF4rfu6ANRgwmoLSiT7kOO5MagPI+UgHYmE1QaNFU3QNBQmS0y1iOPXz1aDG3nF+1YqfQtp7aWsfQYjasIuNGbDBia3lrfnMYUD7Bhon7z/uU8L+s0XXuvZVQY3+g1JobbGjIM0zrx2PCXQciBKeAtwkLsj7ajufiQFU8mTbDeB+vkluZDLZfPoCADn2ldVx4WkoQ2YegWrT/BFAR75K3+caa+PmBd2dKRWr40X3mue8Yh4HK2KGkTK0h+MDzIzznPCaEhjrSDwioM0l4AaShBMHTD3fzuJwlPh/63bpro4nPJu0VBVDtzsDTadzIHfTdgqi9GbWIiZIBxHurAM6Lw4XdCIdHIZeHLF291xw+rSDYlRr/yjuS2Nq4io58ov+g==
  template:
    metadata:
      name: grafana-credentials
      namespace: grafana
