---
- name: Role Facts
  ansible.builtin.include_role:
    name: '{{ role }}'
    tasks_from: facts
  loop:
    - k3s
  loop_control:
    loop_var: role

- name: Role Provisioning
  when: inventory_hostname in k3s_map.server.hosts
  block:
    - name: Validate service state
      ansible.builtin.wait_for:
        port: '{{ k3s_vars.server.api.port }}'
        timeout: 30
      any_errors_fatal: true

    - name: Install
      run_once: true
      block:
        - name: Create sealed-secrets namespace
          kubernetes.core.k8s:
            name: sealed-secrets
            api_version: v1
            kind: Namespace
            state: present
          register: sealed_secrets_result
          delay: 1
          retries: 3
          until: sealed_secrets_result is not failed
          run_once: true

        - name: Install secret key
          kubernetes.core.k8s:
            definition:
              apiVersion: v1
              kind: Secret
              type: kubernetes.io/tls
              metadata:
                name: sealed-secrets-key
                namespace: sealed-secrets
              data:
                tls.key: '{{ sealed_secrets.key | b64encode  }}'
                tls.crt: '{{ sealed_secrets.cert | b64encode  }}'
            kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
            wait: true
          register: sealed_secrets_result
          delay: 1
          retries: 3
          until: sealed_secrets_result is not failed
          run_once: true
          no_log: true

        - name: Install Sealed Secrets
          kubernetes.core.k8s:
            definition: "{{ lookup('kubernetes.core.kustomize', dir='{{ role_path }}/../../kubernetes/controllers/sealed-secrets', enable_helm=True) }}"
            kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
            wait: true
          register: sealed_secrets_result
          delay: 1
          retries: 3
          until: sealed_secrets_result is not failed
          run_once: true
